### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by finnius25** [finnius25/react-to-do#2]
- [x] install nano id
- [x] display todo list
- [x] style to do list
