### ISSUE TITLE
todo List Element

### ISSUE THREAD

**Issue by finnius25** [finnius25/react-to-do#4]
- [x] capitalize first letter
- [x] add delete btn
- [x] add some sort of index or complete btn
